[redis]
    max_idle = 10
    timeout = 10
    db = 1
    host = "127.0.0.1:6379"
    password = ""

[log]
    filepath = ""

[mysql]
  dsn = 'root:root@tcp(127.0.0.1:3306)/test?charset=utf8&parseTime=true'
  idle_conns =  100
  max_conns =  3000
  idle_timeout =  600
  open_orm_stdout = true